[package]
name = "echobot"
version = "0.1.0"
authors = ["pbzweihander <sd852456@naver.com>"]

[dependencies]
reqwest = "0.7"
tungstenite = "0.4"
url = "1.5"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
regex = "0.2"
